Updated release scripts to use svn instead of cvs.

diff --git a/bin/akdrelease b/bin/akdrelease
--- a/bin/akdrelease
+++ b/bin/akdrelease
@@ -1,21 +1,23 @@
 #!/bin/bash
 
-###BUILD_DIR=~/_Developer/CocoaProjects/AKDBUILD
 BUILD_DIR=~/AKDBUILD
 
 if [ ! "${1}" ]; then
     echo "USAGE:"
     echo "  `basename ${0}` <releasenumber>"
     echo
-    echo "  This script builds AppKiDo release tarballs from a fresh checkout."
-    echo "  If you pass 0.95 for the release number, it will check out the"
-    echo "  version tagged as release-0-95 and create tarballs with '0.95' in"
-    echo "  their names.  This script uses $BUILD_DIR as a staging area."
+    echo "  Builds release tarballs for AppKiDo, AppKiDo-for-iPhone, and the"
+    echo "  AppKiDo source, using $BUILD_DIR as a staging area."
     echo
-    echo "  Dots in the release number will be converted to dashes, and"
+    echo "  Dots in <releasenumber> will be converted to dashes, and"
     echo "  \"release-\" will be prepended.  If you pass 0.95 for the release"
-    echo "  number, the tag used will be release-0-95, because tags can't"
-    echo "  contain dots."
+    echo "  number, the tag used will be release-0-95.  This is a historical"
+    echo "  artifact, due to the fact that AppKiDo used to be in CVS, and CVS"
+    echo "  tags can't contain dots."
+    echo
+    echo "  Make sure <releasenumber> is a nicely formed release number."
+    echo "  This script doesn't check for whitespace or any other characters"
+    echo "  that are special to the shell."
     echo
     echo "EXAMPLE:"
     echo "  `basename ${0}` 0.95"
@@ -23,56 +25,70 @@ if [ ! "${1}" ]; then
 fi
 
 AKD_VERSION=${1}
-RELEASE_TAG=release-`echo $AKD_VERSION | sed -e "s/\./-/g"`
+RELEASE_TAG=release-`echo ${AKD_VERSION} | sed -e "s/\./-/g"`
+SVN_ROOT=http://svn.appkido.com/svn/appkido
+
 DEPLOYMENT_BUILD_DIR=$BUILD_DIR/AppKiDo/build/Deployment
 AKD_EXECUTABLE=$DEPLOYMENT_BUILD_DIR/AppKiDo.app/Contents/MacOS/AppKiDo
-APP_TARBALL_PATH=$BUILD_DIR/AppKiDo-$AKD_VERSION.tgz
+AKD_FOR_IPHONE_EXECUTABLE=$DEPLOYMENT_BUILD_DIR/AppKiDo-for-iPhone.app/Contents/MacOS/AppKiDo-for-iPhone
+AKD_TARBALL_PATH=$BUILD_DIR/AppKiDo-$AKD_VERSION.tgz
+AKD_FOR_IPHONE_TARBALL_PATH=$BUILD_DIR/AppKiDo-for-iPhone-$AKD_VERSION.tgz
 SRC_TARBALL_PATH=$BUILD_DIR/AppKiDo-$AKD_VERSION-src.tgz
 
 echo
-echo ===== BUILDING APPKIDO =====
+echo "===== BUILDING APPKIDO ====="
 
 echo
-echo Preparing staging area $BUILD_DIR...
+echo "Preparing staging area $BUILD_DIR..."
 mkdir -p $BUILD_DIR
 cd $BUILD_DIR
+
+echo
+echo "Deleting $BUILD_DIR/AppKiDo if it exists..."
 rm -rf $BUILD_DIR/AppKiDo
 
 echo
-echo Checking out the source tree using tag $RELEASE_TAG...
-###cvs export -D now AppKiDo
-cvs export -r "$RELEASE_TAG" AppKiDo || exit
+echo "Checking out the source tree using tag $RELEASE_TAG..."
+svn export $SVN_ROOT/tags/$RELEASE_TAG AppKiDo || exit
+
+
+
+exit
+
+
 
 echo
-echo Tarring up the source...
+echo "Tarring up the source..."
 tar -C $BUILD_DIR -czf $SRC_TARBALL_PATH AppKiDo
 
 echo
-echo Building the app...
+echo "Building the app..."
 cd $BUILD_DIR/AppKiDo
-##xcodebuild -target AppKiDo -configuration Deployment || exit
-xcodebuild -activetarget -configuration Deployment || exit
+xcodebuild -target All -configuration Deployment || exit
+##xcodebuild -activetarget -configuration Deployment || exit
 
 echo
-echo Stripping the executable...
-echo   -- size BEFORE is `stat -n -f "%z" $AKD_EXECUTABLE`
+echo "Stripping the executable..."
+echo "  -- size BEFORE is `stat -n -f "%z" $AKD_EXECUTABLE`"
 strip $AKD_EXECUTABLE
-echo   -- size AFTER  is `stat -n -f "%z" $AKD_EXECUTABLE`
+echo "  -- size AFTER  is `stat -n -f "%z" $AKD_EXECUTABLE`"
 
 echo
-echo Tarring up the application...
-tar -C $DEPLOYMENT_BUILD_DIR -czf $APP_TARBALL_PATH AppKiDo.app
+echo "Tarring up the application..."
+tar -C $DEPLOYMENT_BUILD_DIR -czf $AKD_TARBALL_PATH AppKiDo.app
 
 echo
-echo Sizes:
-echo   -- app tarball is $APP_TARBALL_PATH
-##echo   -- size of app tarball is `stat -n -f "%z" $APP_TARBALL_PATH`
-echo   -- size of app tarball is `du -h "$APP_TARBALL_PATH" | cut -f 1`
-echo   -- source tarball is $SRC_TARBALL_PATH
-##echo   -- size of source tarball is `stat -n -f "%z" $SRC_TARBALL_PATH`
-echo   -- size of source tarball is `du -h "$SRC_TARBALL_PATH" | cut -f 1`
+echo "Sizes:"
+echo "  -- AppKiDo tarball is $AKD_TARBALL_PATH"
+##echo "  -- size of app tarball is `stat -n -f "%z" $AKD_TARBALL_PATH`"
+echo "  -- size of AppKiDo tarball is `du -h "$AKD_TARBALL_PATH" | cut -f 1`"
+echo "  -- AppKiDo-for-iPhone tarball is $AKD_TARBALL_PATH"
+echo "  -- size of AppKiDo-for-iPhone tarball is `du -h "$AKD_FOR_IPHONE_TARBALL_PATH" | cut -f 1`"
+echo "  -- source tarball is $SRC_TARBALL_PATH"
+##echo "  -- size of source tarball is `stat -n -f "%z" $SRC_TARBALL_PATH`"
+echo "  -- size of source tarball is `du -h "$SRC_TARBALL_PATH" | cut -f 1`"
 
 echo
-echo ===== DONE =====
+echo "===== DONE ====="
 echo
 
